### ISSUE TITLE
Failed to parse source map - Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by epomatti** [MetaMask/detect-provider#42] opened 2022-02-26 14:18 UTC
I've added the dependency: `npm i @metamask/detect-provider`

But getting this error:

```
Failed to parse source map from '/home/pomatti/pjs/uniswap/uniswap-widget/node_modules/@metamask/detect-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/pomatti/pjs/uniswap/uniswap-widget/node_modules/@metamask/detect-provider/src/index.ts'
```

Only thing I'm doing is importing it:

```js
import detectEthereumProvider from '@metamask/detect-provider';
```

No idea why it is complaining:

![image](https://user-images.githubusercontent.com/6530769/155846476-057b3e66-dd06-40ce-a88e-12467be8dd20.png)

**Comment by jack77121** [comment] 2022-03-06 12:31
just came from [here](https://github.com/NoahZinsmeister/web3-react/issues/413), looks pretty similar

**Comment by mcmire** [comment] 2022-03-07 17:30
Where are you getting the error, is it when you install the package or somewhere in your editor? If it's coming from your editor, this seems like an editor issue. There are no references to `src/index.ts` in the distributed version of this package, and [the source map for `dist/index.js` is base64-encoded](https://unpkg.com/browse/@metamask/detect-provider@1.2.0/dist/index.js). Have you seen similar errors from other packages you've installed in the past?

**Comment by epomatti** [comment] 2022-03-07 18:01
When I was running the code I suppose, I'm not working on it anymore.

**Comment by mcmire** [comment] 2022-03-07 22:04
Gotcha. Is it okay with you if I close this then?

**Comment by Mik3y-F** [comment] 2022-03-25 09:51
This is still an issue for me when using typescript react I get the Error: ENOENT: no such file or directory.

**Comment by ckt22** [comment] 2022-03-27 13:23
I had the exact same issue as reported by @epomatti. I am using npm for my React project.

I was using another web3 package called useDapp, which probably has some dependencies with this particular package. And similarly, it was trying to look for index.ts while it should be index.d.ts.

<img width="688" alt="螢幕截圖 2022-03-27 下午9 17 33" src="https://user-images.githubusercontent.com/54921960/160283347-ab38464e-c2a5-400b-8207-97d2d41a41ec.png">

I tried to fix the issue by downloading this particular package with npm. But the problem still exists.

@mcmire So you said that there is some similar approaches to resolve the issue. Would you please share the solution? Thanks!

**Comment by alxlacayo** [comment] 2022-03-30 08:36
I too am getting this error message in a fresh create-react-app. 

Steps to reproduce:
1. Run npx create-react-app my-app
2. Run npm i @metamask/detect-provider
3. import detectEthereumProvider from '@metamask/detect-provider' in App.js
4. npm start 

WARNING in ./node_modules/@metamask/detect-provider/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/XXXXXX/Desktop/my-app/node_modules/@metamask/detect-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/XXXXX/Desktop/my-app/node_modules/@metamask/detect-provider/src/index.ts'
 @ ./src/App.js 6:0-63
 @ ./src/index.js 7:0-24 11:33-36

**Comment by deni-nodeify** [comment] 2022-03-31 23:11
@alxlacayo  Did you manage to solve this? I am getting the same error message.

**Comment by alxlacayo** [comment] 2022-04-01 05:41
@deni-nodeify I have not. Let me know if you do though.

**Comment by deni-nodeify** [comment] 2022-04-01 10:00
@alxlacayo Actually I figured out how to solve this. 
If you are using useDapp switch to v0.9.1
Get  @metamask/detect-provider v1.2.0
and the latest version of react-scripts. 

Run "npm audit fix --force"  and I think you'll fix your problem.

**Comment by alxlacayo** [comment] 2022-04-03 10:55
@deni-nodeify I'm still having this issue but I'm assuming it's because I'm using typescript? Are you using typescript?

**Comment by mcmire** [comment] 2022-04-03 21:49
Thanks @alxlacayo, I was able to reproduce this error. I believe this is happening because the source map is referring to `index.ts`, which doesn't exist in the published version. I believe if we add this to `tsconfig.json` it should work:

```
"inlineSources": true
```

but I'll have to test this with `create-react-app`.

**Comment by alxlacayo** [comment] 2022-04-04 06:00
@mcmire gave it a try but am still seeing the error

**Comment by bitwineth** [comment] 2022-04-10 03:55
same problem

**Comment by mcmire** [comment] 2022-04-11 15:39
@alxlacayo Just to be clear, it wouldn't be added to _your_ `tsconfig.json`, it would need to be added to the `tsconfig.json` in this project and a new version of `detect-provider` would need to be published.

**Comment by FStanczyk** [comment] 2022-05-05 22:37
Please help me with this issue, problem started when I tried to add provider but did not stop even after deleting that...
My entire project stopped working. 
Error: ENOENT: no such file or directory, open 'C:\Users\x\OneDrive\x\x\x\node_modules\@metamask\detect-provider\src\index.ts'

**Closed** 2022-05-09 22:10 UTC

**Comment by Entity54** [comment] 2022-05-21 13:21
Hi All,
We have the same issue with our create-react-app. When running in localhost we get the following
"Failed to parse source map from node_modules/@metamask/detect-provider/src/index.ts' file: Error: ENOENT: no such file or directory ..."
but the Dapp runs perfectly fine

However when trying to deploy to Vercel (or similar) it becomes impossible because of this message

**Comment by paysage** [comment] 2022-07-27 09:10
same error, is there any solution?

**Comment by codeclouds-team** [comment] 2022-08-13 06:39
downgrading the version resolved my issue.
@metamask/detect-provider": "1.0.0

**Comment by mcmire** [comment] 2022-08-15 21:23
We are trying to get a new version out the door that should solve this issue. Sorry for the wait folks :)

**Comment by advra** [comment] 2022-09-30 22:28
Any updates? Having same issues still

**Comment by mcmire** [comment] 2022-09-30 23:18
Ah. I started making a new release and never finished it. Sorry for dropping the ball on this, I'll make a reminder to take care of this next week.

**Comment by mcmire** [comment] 2022-11-23 18:16
Sorry for the late reply on this issue.

This problem should be fixed with 2.0.0, so if you're still experiencing this issue, try updating to that version!

**Comment by javaspeak** [comment] 2023-10-24 19:03
I had Failed to parse source maps Warnings as well.

My solution to reduce the noise was to edit my config-overrides.js and add:

```
module.exports = function override(config, env) {
  //do stuff with the webpack config...

  // This is added because complaining about parsing source maps of walletconnect
  config.ignoreWarnings = [/Failed to parse source map/];

  return config;
}
```

Note you can comment out this line to see the warnings:

     config.ignoreWarnings = [/Failed to parse source map/];

See:

https://github.com/spotadev/symbiont-wallet-sign-web

Note for those of you who do not know config-overides.js I created my project as follows:


(i) npx create-react-app . --template typescript


(ii) npm install react-app-rewired --save-dev


(iii) Create a config-overrides.js file in the root directory

  Add:

    module.exports = function override(config, env) {
      //do stuff with the webpack config...
      return config;
    }


(iv) Change package.json

    "scripts": {
  -   "start": "react-scripts start",
  +   "start": "react-app-rewired start",
  -   "build": "react-scripts build",
  +   "build": "react-app-rewired build",
  -   "test": "react-scripts test",
  +   "test": "react-app-rewired test",
      "eject": "react-scripts eject"

The idea with react-app-rewired is that you do not need to eject your config into files to change behaviour - instead you just create the  config-overrides.js file and override stuff there.

**Comment by mcmire** [comment] 2023-11-03 00:24
Hi @javaspeak, sorry to hear you're still encountering those errors. Which version are you using?
